### ISSUE TITLE
Transfer maintenance rights to The Foreman

### ISSUE THREAD

**Issue by sandfoxme** [theforeman/journald-native#6]
* [x] Transfer GitHub repo
* [x] Transfer Rubygems release rights
* [x] Archive BitBucket and Gitlab repos

**Comment by GregSutcliffe** [comment]
Sending an invite as per https://github.com/sandfoxme/journald-logger/issues/4#issuecomment-428193252

**Comment by sandfoxme** [comment]
done here too

**Comment by GregSutcliffe** [comment]
Thanks! I've added you and @lzap to repo with admin rights, and added @lzap to the rubygem.
